[package]
name = "upio-core"
description = "Core types, traits, and utilities for the upio ecosystem"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
image = { workspace = true }
mime_guess = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
zip = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
parking_lot = "0.12"
