[package]
name = "uploader-goonbox"
description = "GoonBox (goonbox.cr) uploader implementation"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
upio-core = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
dirs = { workspace = true }
futures = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
chaser-oxide = { workspace = true }
rand = { workspace = true }
